In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# task 1 and 4
#P = np.matrix([[0.1, 0.1, 0.2, 0.6],[0.1, 0.2, 0.3, 0.4],[0.1, 0.5, 0, 0.4],[0, 0.2, 0, 0.8]])
P = np.matrix([[0.2,0.2,0.4,0.2],[0.2,0.1,0.5,0.2],[0.7,0.1,0.1,0.1],[0.4,0,0.5,0.1]])
p0 = np.array([0.1, 0.2, 0.2, 0.5])
dimP = len(p0)
n = 10
print("n = ", n, '\n')
print("Матриця переходів \n{}\nПочатковий вектор \n{}\n".format(P, p0))
stoch_number = round(np.random.uniform(0, 1), 3)
number = 0.43
print("Випадкове число = {}\nЗадане число = {}\n".format(stoch_number, number))
Pm = []
for i in range(dimP):
    Pi = [round(np.sum(P[i, :j]), 5) for j in range(1, dimP+1)]
    Pi.insert(0, 0)
    Pm.append(Pi)
p0_temp = list(p0)
p0_temp.insert(0, 0)
p0_i = [round(np.sum(p0_temp[:i]), 5) for i in range(1, dimP+2)]
realiz_n = []
realiz_s = []
for i in range(1, dimP+1):
    if number > p0_i[i-1] and number < p0_i[i]:
        realiz_n.append(i-1)
        break
for i in range(1, dimP+1):
    if stoch_number > p0_i[i-1] and stoch_number < p0_i[i]:
        realiz_s.append(i-1)
        break
i = 1
while i < n:
    realiz_n[i-1]
    for j in range(1, dimP+1):
        if number > Pm[realiz_n[i-1]][j-1] and number <= Pm[realiz_n[i-1]][j]:
            realiz_n.append(j-1)
            break
    i+=1
realiz_n = np.array(realiz_n) + 1
print("Початковий стан при заданому початковому стані:",realiz_n[0])
print("Реалізації марківського процесу при заданому початковому стані із кількістю кроків n = {} \n {}".format(n, realiz_n))
i = 1
while i < n:
    realiz_s[i-1]
    for j in range(1, dimP+1):
        if stoch_number > Pm[realiz_s[i-1]][j-1] and stoch_number <= Pm[realiz_s[i-1]][j]:
            realiz_s.append(j-1)
            break
    i+=1
realiz_s = np.array(realiz_s) + 1
print("Початковий стан при випадковому початковому стані:",realiz_s[0])
print("Реалізації марківського процесу при випадковому початковому стані із кількістю кроків n = {} \n {}".format(n, realiz_s))

n =  10 

Матриця переходів 
[[0.2 0.2 0.4 0.2]
 [0.2 0.1 0.5 0.2]
 [0.7 0.1 0.1 0.1]
 [0.4 0.  0.5 0.1]]
Початковий вектор 
[0.1 0.2 0.2 0.5]

Випадкове число = 0.707
Задане число = 0.43

Початковий стан при заданому початковому стані: 3
Реалізації марківського процесу при заданому початковому стані із кількістю кроків n = 10 
 [3 1 3 1 3 1 3 1 3 1]
Початковий стан при випадковому початковому стані: 4
Реалізації марківського процесу при випадковому початковому стані із кількістю кроків n = 10 
 [4 3 2 3 2 3 2 3 2 3]


In [3]:
# task 2
P = np.matrix([[1, 0, 0, 0, 0],[0, 1, 0, 0, 0],[0.3, 0.1, 0.3, 0.1, 0.2],[0.3, 0.1, 0.3, 0.1, 0.2],[0.1, 0.5, 0.2, 0.1, 0.1]])
p0 = np.array([0.1, 0.2, 0.2, 0.25, 0.25])
dimP = len(p0)
n = 10
print("n = ", n, '\n')
print("Матриця переходів \n{}\nПочатковий вектор \n{}\n".format(P, p0))
stoch_number = round(np.random.uniform(0, 1), 3)
number = 0.76
print("Випадкове число = {}\nЗадане число = {}\n".format(stoch_number, number))
Pm = []
for i in range(dimP):
    Pi = [round(np.sum(P[i, :j]), 5) for j in range(1, dimP+1)]
    Pi.insert(0, 0)
    Pm.append(Pi)
p0_temp = list(p0)
p0_temp.insert(0, 0)
p0_i = [round(np.sum(p0_temp[:i]), 5) for i in range(1, dimP+2)]
realiz_n = []
realiz_s = []
for i in range(1, dimP+1):
    if number > p0_i[i-1] and number < p0_i[i]:
        realiz_n.append(i-1)
        break
for i in range(1, dimP+1):
    if stoch_number > p0_i[i-1] and stoch_number < p0_i[i]:
        realiz_s.append(i-1)
        break
i = 1
while i < n:
    realiz_n[i-1]
    for j in range(1, dimP+1):
        if number > Pm[realiz_n[i-1]][j-1] and number <= Pm[realiz_n[i-1]][j]:
            realiz_n.append(j-1)
            break
    i+=1
realiz_n = np.array(realiz_n) + 1
print("Початковий стан при заданому початковому стані:",realiz_n[0])
print("Реалізації марківського процесу при заданому початковому стані із кількістю кроків n = {} \n {}".format(n, realiz_n))
i = 1
while i < n:
    realiz_s[i-1]
    for j in range(1, dimP+1):
        if stoch_number > Pm[realiz_s[i-1]][j-1] and stoch_number <= Pm[realiz_s[i-1]][j]:
            realiz_s.append(j-1)
            break
    i+=1
realiz_s = np.array(realiz_s) + 1
print("Початковий стан при випадковому початковому стані:",realiz_s[0])
print("Реалізації марківського процесу при випадковому початковому стані із кількістю кроків n = {} \n {}".format(n, realiz_s))

n =  10 

Матриця переходів 
[[1.  0.  0.  0.  0. ]
 [0.  1.  0.  0.  0. ]
 [0.3 0.1 0.3 0.1 0.2]
 [0.3 0.1 0.3 0.1 0.2]
 [0.1 0.5 0.2 0.1 0.1]]
Початковий вектор 
[0.1  0.2  0.2  0.25 0.25]

Випадкове число = 0.785
Задане число = 0.76

Початковий стан при заданому початковому стані: 5
Реалізації марківського процесу при заданому початковому стані із кількістю кроків n = 10 
 [5 3 4 4 4 4 4 4 4 4]
Початковий стан при випадковому початковому стані: 5
Реалізації марківського процесу при випадковому початковому стані із кількістю кроків n = 10 
 [5 3 4 4 4 4 4 4 4 4]


In [106]:
#task 3
def get_state(pn, p):
    F = pn[0]
    i = 0
    while(F < p):
        i = i + 1
        F = F + pn[i]
    return i
def get_I_size(stan_matr):
    I_size = 0
    size_matr = len(stan_matr[0, :])
    for i in range(size_matr):
        if(stan_matr[i, i] == 1):
            I_size = I_size + 1
    return I_size
def eye(dimens):
    return np.diag(np.diag([[1]*dimens]*dimens))
n = 5
p01 = [0, 0, 1, 0, 0]
p02 = [0.1, 0.2, 0.3, 0.3, 0.1]
m = 10
states1 = []
states2 = []
P = np.array([[1, 0, 0, 0, 0],[0, 1, 0, 0, 0],[0.3, 0.1, 0.3, 0.1, 0.2],[0.3, 0.1, 0.3, 0.1, 0.2],[0.1, 0.5, 0.2, 0.1, 0.1]])
ps1 = np.random.uniform(0, 1, m + 1)
ps2 = np.random.uniform(0, 1, m + 1)
pn1 = []
pn2 = []
print("P",P)
P_size = len(P[:, 0])
I_size = get_I_size(P)
I = eye(I_size)
#print("I", I)
R = P[I_size:P_size, :I_size]
Q = P[I_size:P_size, I_size:P_size]
# print("R", R)
# print("Q",Q)
# print(eye(P_size - I_size) - Q)
M = np.linalg.inv(eye(P_size - I_size) - Q)
pi_vector1 = p01[I_size:P_size]
tau_vector1 = np.dot(M, pi_vector1)
B = np.dot(M, R)
t_absorp1 = sum(tau_vector1)
tau_vector_exp1 = [i for i in range(0, P_size - I_size)]
t_absorp_exp1 = 0
states1.append(get_state(p01, ps1[0]))
for i in range(m):
    states1.append(get_state(list(P[states1[i], :]), ps1[i + 1]))
    if(states1[i] > I_size):
        tau_vector_exp1[states1[i] - I_size] = tau_vector_exp1[states1[i] - I_size] + 1
t_absorp_exp1 = sum(tau_vector_exp1)
pi_vector2 = p02[I_size:P_size]
tau_vector2 = np.dot(M, pi_vector2)
t_absorp2 = sum(tau_vector2)
tau_vector_exp2 = [i for i in range(0, P_size - I_size)]
t_absorp_exp2 = 0
states2.append(get_state(p02, ps2[1]))
for i in range(m):
    states2.append(get_state(list(P[states2[i], :]), ps2[i + 1]))
    if(states2[i] > I_size):
        tau_vector_exp2[states1[i] - I_size] = tau_vector_exp2[states1[i] - I_size] + 1
print(I)
t_absorp_exp2 = sum(tau_vector_exp2)
print("Вірогідність поглинання:")
print(B)
print("Точний стан:")
print("Середня тривалість перебування в відповідних станах:")
print(tau_vector1)
print("Середній час поглинання:")
print(t_absorp1)
print("Середня тривалість перебування у відповідних станах (експериментальні):")
print(tau_vector_exp1)
print("Середній час поглинання(експериментальний):")
print(t_absorp_exp1)
print("Нестабільний стан:")
print("Середня тривалість перебування в відповідних станах:")
print(tau_vector2)
print("Середній час поглинання:")
print(t_absorp2)
print("Середня тривалість перебування у відповідних станах (експериментальні):")
print(tau_vector_exp2)
print("Середній час поглинання(експериментальний):")
print(t_absorp_exp2)


P [[1.  0.  0.  0.  0. ]
 [0.  1.  0.  0.  0. ]
 [0.3 0.1 0.3 0.1 0.2]
 [0.3 0.1 0.3 0.1 0.2]
 [0.1 0.5 0.2 0.1 0.1]]
[[1 0]
 [0 1]]
Вірогідність поглинання:
[[0.60416667 0.39583333]
 [0.60416667 0.39583333]
 [0.3125     0.6875    ]]
Точний стан:
Середня тривалість перебування в відповідних станах:
[1.64583333 0.64583333 0.4375    ]
Середній час поглинання:
2.729166666666666
Середня тривалість перебування у відповідних станах (експериментальні):
[0, 1, 2]
Середній час поглинання(експериментальний):
3
Нестабільний стан:
Середня тривалість перебування в відповідних станах:
[0.60416667 0.60416667 0.3125    ]
Середній час поглинання:
1.520833333333333
Середня тривалість перебування у відповідних станах (експериментальні):
[0, 1, 2]
Середній час поглинання(експериментальний):
3


In [105]:
#task 5
def get_state(pn, p):
    F = pn[0]
    i = 0
    while(F < p):
        i = i + 1
        F = F + pn[i]
    return i
def eye(dimens):
    return np.diag(np.diag([[1]*dimens]*dimens))
def get_V(P, m):
    P_size = len(P[0, :])
    V = np.array([[0]*P_size]*P_size)
    P_pow = eye(P_size)
    for i in range(m):
        P_pow = np.dot(P_pow, P)
        V = V + P_pow
    return V
def get_M (Z, f):
    size = len(f)
    I = eye(size)
    E = np.array([[1]*size]*size)
    DZ = np.diag(np.diag(Z))
    DM = np.diag(np.diag([[1/size]*size]*size))
    M = np.dot((I - Z + np.dot(E, DZ)), DM)
    return M
  
n = 5
p01 = [0, 0, 1, 0, 0]
p02 = [0.1, 0.2, 0.3, 0.3, 0.1]
m = 100
states1 = []
states2 = []
P = np.array([[0.2,0.1,0.1,0.4,0.2],[0.2,0.1,0.5,0,0.2],[0.6,0.1,0.1,0.1,0.1],[0.4,0,0.5,0,0.1],[0.4,0.3,0,0.3,0]])
#P = np.array([[1/n]*n]*n)
ps1 = np.random.uniform(0, 1, m + 1)
ps2 = np.random.uniform(0, 1, m + 1)
pn1 = []
pn2 = []
P_size = len(P[0, :])
F = P
for i in range(100):
    F = np.dot(F, P)
f = F[0, :]
Z = np.linalg.inv(eye(P_size) - (P - F))
V = get_V(P, m)
M = get_M(Z, f)
tn1 = np.dot(p01,V)
t1 = np.dot(p01,M)
states1.append(get_state(p01, ps1[0]))
tn_exp1 = [i for i in range(P_size )]
t_exp1 = [i for i in range(P_size )]
for i in range(m):
    states1.append(get_state(P[states1[i], :], ps1[i + 1]))
    tn_exp1[states1[i]] = tn_exp1[states1[i]] + 1
    if(t_exp1[states1[i]] == 0):
        t_exp1[states1[i]] = i
tn2 = np.dot(p02,V)
t2 = np.dot(p02,M)
states2.append(get_state(p02, ps2[0]))
tn_exp2 = [i for i in range(P_size )]
t_exp2 = [i for i in range(P_size )]
for i in range(m):
    states2.append(get_state(P[states2[i], :], ps2[i + 1]))
    tn_exp2[states2[i]] = tn_exp2[states2[i]] + 1
    if(t_exp2[states2[i]] == 0):
        t_exp2[states2[i]] = i
print("Фінальна матриця F:")
print(F)
print("Z:")
print(Z)
print("Середня тривалість переміщення між відповідними станами:")
print(V)
print("Середні моменти першого трансферу між відповідними станами:")
print(M)
print("Точний стан:")
print("Середня тривалість перебування в відповідних станах:")
print(tn1)
print("Середні моменти першого прибуття в відповідні стани:")
print(t1)
print("Середня тривалість перебування в відповідних станах (експериментальна):")
print(tn_exp1)
print("Середні моменти першого прибуття в відповідні стани (експериментальні):")
print(t_exp1)
print("Нестабільний стан:")
print("Середня тривалість перебування в відповідних станах:")
print(tn2)
print("Середні моменти першого прибуття в відповідні стани:")
print(t2)
print("Середня тривалість перебування в відповідних станах (експериментальна):")
print(tn_exp2)
print("Середні моменти першого прибуття в відповідні стани (експериментальні):")
print(t_exp2)


Фінальна матриця F:
[[0.35054755 0.10639769 0.209683   0.20092219 0.13244957]
 [0.35054755 0.10639769 0.209683   0.20092219 0.13244957]
 [0.35054755 0.10639769 0.209683   0.20092219 0.13244957]
 [0.35054755 0.10639769 0.209683   0.20092219 0.13244957]
 [0.35054755 0.10639769 0.209683   0.20092219 0.13244957]]
Z:
[[ 0.86698642 -0.01221417 -0.05755789  0.15457868  0.04820696]
 [-0.0938205   1.02467344  0.21448822 -0.20046455  0.05512339]
 [ 0.18744752 -0.00472137  0.87270148 -0.04253948 -0.01288814]
 [ 0.08946481 -0.09694039  0.1925862   0.84506859 -0.03017921]
 [-0.00505969  0.16703655 -0.11058383  0.05429049  0.89431647]]
Середня тривалість переміщення між відповідними станами:
[[34.92174146 10.62755528 20.91074182 20.2467977  13.29316373]
 [34.96093455 10.66444289 21.18278793 19.89175447 13.30008016]
 [35.24220256 10.63504808 20.84100119 20.04967954 13.23206863]
 [35.14421985 10.54282906 21.16088591 19.93728761 13.21477757]
 [35.04969535 10.806806   20.85771589 20.14650951 13.13927324

In [30]:
#task 1
def get_state(pn, p):
    F = pn[0]
    i = 0
    while(F < p):
        i = i + 1
        F = F + pn[i]
    return i
n = 5
p01 = [0, 0, 1, 0, 0]
p02 = [0.1, 0.2, 0.3, 0.3, 0.1]
m = 10
states1 = list()
states2 = list()
P = [[1/n]*n]*n
#P[0] = [1, 0, 0, 0, 0]
ps1 = np.random.uniform(0, 1, m+1)
ps2 = np.random.uniform(0, 1, m+1)
print(P)

print(ps1)
pn1 = list()
pn2 = list()
states1.append(get_state(p01, ps1[0]))
print(states1)
for i in range(m):
    states1.append(get_state(P[states1[i]], ps1[i + 1]))

states2.append(get_state(p02, ps2[0]))
for i in range(m):
    states2.append(get_state(P[states2[i]], ps2[i + 1]))
print(states1)
print(states2)


[[0.2, 0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2, 0.2]]
[0.14933988 0.58891111 0.34026933 0.36495886 0.66623339 0.7189737
 0.56323226 0.89584097 0.72658575 0.16264532 0.80208452]
[2]
[2, 2, 1, 1, 3, 3, 2, 4, 3, 0, 4]
[3, 4, 3, 4, 4, 1, 2, 3, 3, 1, 3]
